apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  ports:
    - port: 8080
  selector:
    app: webservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: stephanebrillant/inf36307:rest-api
        ports:
        - containerPort: 8080
        resources:
          requests:  # Garantit min, évite starvation
            cpu: "4"  # 4 CPUs (4000m) ou 80% si moins
            memory: 8Gi  # 8192Mi
          limits:  # Max dur, évite pod monopoliser node
            cpu: "6"  # 6 CPUs
            memory: 12Gi  # 12288Mi